### ISSUE TITLE
ERROR: Unable to copy database file. Caused by: java.io.FileNotFoundException: PoliticalSquare.db

### ISSUE THREAD

**Issue by donenoyes** [ant-fedorich/political-square#5]
ERROR
```
021-04-03 16:05:47.580 8047-8047/eltonio.projects.politicalsquare E/AndroidRuntime: FATAL EXCEPTION: main
    Process: eltonio.projects.politicalsquare, PID: 8047
    java.lang.RuntimeException: Unable to copy database file.
        at androidx.room.SQLiteCopyOpenHelper.verifyDatabaseFile(SQLiteCopyOpenHelper.java:131)
        at androidx.room.SQLiteCopyOpenHelper.getWritableDatabase(SQLiteCopyOpenHelper.java:87)
        at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
        at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
        at androidx.room.RoomDatabase.query(RoomDatabase.java:324)
        at androidx.room.util.DBUtil.query(DBUtil.java:83)
        at eltonio.projects.politicalsquare.repository.QuestionDao_Impl$2.call(QuestionDao_Impl.java:90)
        at eltonio.projects.politicalsquare.repository.QuestionDao_Impl$2.call(QuestionDao_Impl.java:87)
        at androidx.room.CoroutinesRoom$Companion$execute$2.invokeSuspend(CoroutinesRoom.kt:54)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.io.FileNotFoundException: PoliticalSquare.db
```

When trying to take the quiz for All World, this error occurs.

What's the fix?

**Comment by ant-fedorich** [comment]
Hi @donenoyes. I have fixed this issue!
See Readme
